// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum com_amap_api_maps_model_AMapPara_LineCapType {
  LineCapButt /* null */,
  LineCapSquare /* null */,
  LineCapArrow /* null */,
  LineCapRound /* null */
}

extension com_amap_api_maps_model_AMapPara_LineCapTypeToX on com_amap_api_maps_model_AMapPara_LineCapType {
  int toValue() {
    switch (this) {
      case com_amap_api_maps_model_AMapPara_LineCapType.LineCapButt: return com_amap_api_maps_model_AMapPara_LineCapType.LineCapButt.index + 0;
      case com_amap_api_maps_model_AMapPara_LineCapType.LineCapSquare: return com_amap_api_maps_model_AMapPara_LineCapType.LineCapSquare.index + 0;
      case com_amap_api_maps_model_AMapPara_LineCapType.LineCapArrow: return com_amap_api_maps_model_AMapPara_LineCapType.LineCapArrow.index + 0;
      case com_amap_api_maps_model_AMapPara_LineCapType.LineCapRound: return com_amap_api_maps_model_AMapPara_LineCapType.LineCapRound.index + 0;
    }
  }
}

extension com_amap_api_maps_model_AMapPara_LineCapTypeFromX on int {
  com_amap_api_maps_model_AMapPara_LineCapType tocom_amap_api_maps_model_AMapPara_LineCapType() {
    switch (this) {
      
      default: return com_amap_api_maps_model_AMapPara_LineCapType.values[this + 0];
    }
  }
}