//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:amap_map_fluttify/src/ios/ios.export.g.dart';
import 'package:amap_map_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
mixin com_autonavi_amap_mapcore_interfaces_IOverlay on java_lang_Object {
  

  

  

  @mustCallSuper
  Future<void> remove() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('remove::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<String> getId() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('getId::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> setZIndex(double var1) {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('setZIndex::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<double> getZIndex() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('getZIndex::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> setVisible(bool var1) {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('setVisible::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<bool> isVisible() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('isVisible::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<bool> equalsRemote(com_autonavi_amap_mapcore_interfaces_IOverlay var1) {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('equalsRemote::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<int> hashCodeRemote() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('hashCodeRemote::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> destroy() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('destroy::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<bool> isAboveMaskLayer() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('isAboveMaskLayer::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> setAboveMaskLayer(bool var1) {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('setAboveMaskLayer::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
}