// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:amap_map_fluttify/src/ios/ios.export.g.dart';
import 'package:amap_map_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

class com_amap_api_maps_model_AMapPara extends java_lang_Object  {
  //region constants
  static final int DOTTEDLINE_TYPE_DEFAULT = -1;
  static final int DOTTEDLINE_TYPE_SQUARE = 0;
  static final int DOTTEDLINE_TYPE_CIRCLE = 1;
  //endregion

  //region creators
  static Future<com_amap_api_maps_model_AMapPara> create__() async {
    final int refId = await MethodChannel('me.yohom/amap_map_fluttify').invokeMethod('ObjectFactory::createcom_amap_api_maps_model_AMapPara__');
    final object = com_amap_api_maps_model_AMapPara()..refId = refId..tag = 'amap_map_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  //endregion

  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  //endregion
}